version: "3.3"

services:

  db:
    platform: linux/amd64
    image: postgres:latest

    ports:
      - "3307:3306"
    networks:
      - dev_net
    environment:
      -  POSTGRES_USER=compare
      -  POSTGRES_PASSWORD=abc123
    volumes:
      - pg_conf:/etc/postgresql
      - pg_log:/var/log/postgresql
      - pg_data:/var/lib/postgresql/data
networks:
  dev_net:
    external:
      name: compare

volumes:
  pg_data:
  pg_conf:
  pg_log:
